{ dmenu, i3status }:
 
''


# This file has been auto-generated by i3-config-wizard(1).# It will not be overwritten, so edit it as you like.  # # Should you change your keyboard layout somewhen, delete # this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!


focus_follows_mouse yes
exec --no-startup-id setxkbmap -layout gb
exec --no-startup-id setxkbmap -device 3 -layout gb
exec --no-startup-id mouskeys
exec --no-startup-id /etc/do.xrandr
exec --no-startup-id xscreensaver --no-splash &

# exec_always --no-startup-id xset dpms 0 0 30 &
# exec_always --no-startup-id xss-lock -- i3lock -n &

# exec syndaemon -dRki1
exec --no-startup-id sleep 2; feh --bg-fill Wallpaper.jpg
set $mod Mod4

set $Left h
set $Right l
set $Down j
set $Up k

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below. ISO 10646 = Unicode
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
font pango:monospace 10
# font pango:DejaVu Sans Mono 160
# font pango:DejaVu Sans Mono, Terminus Bold Semi-Condensed 160
# font pango:Terminus 160px
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, if you need a lot of unicode glyphs or
# right-to-left text rendering, you should instead use pango for rendering and
# chose a FreeType font, such as:
# font pango:DejaVu Sans Mono 12

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+space exec i3-sensible-terminal
bindsym $mod+Ctrl+space exec i3-sensible-terminal -x ssh adrianmay@work
bindsym $mod+b exec chromium
bindsym $mod+Shift+v exec virtualbox
bindsym $mod+s exec slack
bindsym $mod+c exec clementine
bindsym $mod+Ctrl+s exec sudo systemctl suspend
bindsym $mod+t exec --no-startup-id "killall -q syndaemon && synclient TouchpadOff=1 || ( synclient TouchpadOff=0 && syndaemon -dRki1 )"
bindsym $mod+v exec --no-startup-id "mpv --profile=low-latency --untimed rtsp://10.0.0.8/live/main"
bindsym $mod+Shift+q kill
bindsym $mod+q kill
bindsym $mod+n exec --no-startup-id "nosemouse"
bindsym $mod+m exec --no-startup-id "/usr/bin/mouskeys"
bindsym $mod+Prior exec --no-startup-id /etc/do.xrandr
bindsym $mod+Next exec --no-startup-id /etc/dont.xrandr

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# screen lock
# bindsym $mod+BackSpace exec i3lock -c 000010
bindsym $mod+Ctrl+Shift+s exec sudo /sbin/shutdown -h now
# bindsym $mod+Return exec dm-tool switch-to-greeter
# bindsym $mod+Shift+s exec sudo /usr/sbin/pm-suspend
# change focus
bindsym $mod+$Left focus left
bindsym $mod+$Down focus down
bindsym $mod+$Up focus up
bindsym $mod+$Right focus right

bindsym $mod+Ctrl+e exec --no-startup-id "sleep 0.5; xvkbd -text adrian.alexander.may@gmail.com"
# move focused window
bindsym $mod+Shift+$Left move left
bindsym $mod+Shift+$Down move down
bindsym $mod+Shift+$Up move up
bindsym $mod+Shift+$Right move right

# move between monitors
bindsym $mod+Ctrl+$Up move workspace to output up
bindsym $mod+Ctrl+$Down move workspace to output down
bindsym $mod+Ctrl+$Left move workspace to output left
bindsym $mod+Ctrl+$Right move workspace to output right

# split in horizontal orientation
bindsym $mod+Shift+bar split h
# split in vertical orientation
bindsym $mod+Shift+minus split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen

# change container layout (stacked, tabbed, toggle split)
# bindsym $mod+s layout stacking
# bindsym $mod+w layout tabbed
# bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+equal floating toggle
bindsym $mod+Ctrl+equal sticky toggle
# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
bindsym $mod+Shift+a focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10
bindsym $mod+F1 workspace 11
bindsym $mod+F2 workspace 12
bindsym $mod+F3 workspace 13
bindsym $mod+F4 workspace 14
bindsym $mod+F5 workspace 15
bindsym $mod+F6 workspace 16
bindsym $mod+F7 workspace 17
bindsym $mod+F8 workspace 18
bindsym $mod+F9 workspace 19
bindsym $mod+F10 workspace 20

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10
bindsym $mod+Shift+F1 move container to workspace 11
bindsym $mod+Shift+F2 move container to workspace 12
bindsym $mod+Shift+F3 move container to workspace 13
bindsym $mod+Shift+F4 move container to workspace 14
bindsym $mod+Shift+F5 move container to workspace 15
bindsym $mod+Shift+F6 move container to workspace 16
bindsym $mod+Shift+F7 move container to workspace 17
bindsym $mod+Shift+F8 move container to workspace 18
bindsym $mod+Shift+F9 move container to workspace 19
bindsym $mod+Shift+F10 move container to workspace 20

# scrot & gimp - root
bindsym Print exec scrot -e 'mv $f /tmp/ && gimp /tmp/$f'
# # scrot & gimp - select window or rectangle
bindsym Mod1+Print exec scrot -s -e 'mv $f /tmp/ && gimp /tmp/$f'

# reload the configuration file
bindsym $mod+Shift+r reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Ctrl+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+BackSpace exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # same bindings, but for the arrow keys
        bindsym $Left resize shrink width 10 px or 10 ppt
        bindsym $Down resize grow height 10 px or 10 ppt
        bindsym $Up resize shrink height 10 px or 10 ppt
        bindsym $Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}


## Volume control
set $volumepath /etc/config/i3-volume
set $statuscmd i3status

# Signal used to update the status line
#   i3blocks uses SIGRTMIN+10 by default
#   i3status uses SIGUSR1 by default
set $statussig SIGUSR1

# Amount to increase/decrease volume as a percentage
set $volumestep 5

# alsa-utils settings
#
# To configure a default card, see https://www.alsa-project.org/main/index.php/Asoundrc
#
# Card number to control.
#   If not specified, i3-volume will let `amixer` use a default.
#   List cards: aplay -l
#set $alsacard 1

# append "-c $alsacard" without quotes to override default card
bindsym XF86AudioRaiseVolume exec --no-startup-id $volumepath -an -t $statuscmd -u $statussig up $volumestep
bindsym XF86AudioLowerVolume exec --no-startup-id $volumepath -an -t $statuscmd -u $statussig down $volumestep
bindsym XF86AudioMute        exec --no-startup-id $volumepath -an -t $statuscmd -u $statussig mute


''
